language: c
arch: ppc64le
os:
  - linux

compiler:
  - gcc 

jdk: "openjdk8"

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y git tar make gcc g++ wget cmake libboost-all-dev bison flex maven gperf libsnappy-dev libevent-dev automake libtool libjson-perl libreadline-dev
  - sudo apt-get install libapr1 libapr1-dev unzip curl libcurl4-openssl-dev libbz2-dev pkg-config libssl-dev
  - sudo apt-get install libjson-c-dev libxml2-dev python-dev python-setuptools python-pip
  - sudo pip uninstall pyyaml
  - sudo apt-get install libyaml-dev libpython2.7-dev
  - sudo pip install pyyaml
  
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
  - cd /
  - wget http://archive.apache.org/dist/thrift/0.10.0/thrift-0.10.0.tar.gz 
  - tar -xvzf thrift-0.10.0.tar.gz
  - cd thrift-0.10.0
  - ./configure 
  - sudo make
  - sudo make install
  - cd ..
  
  - cd /
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protobuf-all-3.11.2.tar.gz
  - tar -xvzf protobuf-all-3.11.2.tar.gz
  - cd protobuf-3.11.2
  - ./autogen.sh
  - ./configure
  - sudo make
  - sudo make install
  - cd ..
  
before_script:
  - mvn -DskipTests=true apache-rat:check
  - export DEPENDENCY_INSTALL_PREFIX=/usr/local/opt/openssl
  - cd $TRAVIS_BUILD_DIR
  - ./configure 
script:
  - sudo install -o $USER -d /usr/local/hawq
  - make -j$(sysctl -n hw.ncpu)
  - make feature-test
  - make feature-test-clean

branches:
  except:
    - legacy
